// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0BnERLaVYugx44DKXGd8eAaoU9xqt_wM',
    appId: '1:548774862186:web:675df6681d15d961ffd913',
    messagingSenderId: '548774862186',
    projectId: 'talkhands-7d320',
    authDomain: 'talkhands-7d320.firebaseapp.com',
    databaseURL: 'https://talkhands-7d320-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'talkhands-7d320.appspot.com',
    measurementId: 'G-PG8LEB6D1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtqc3bqPf3QaSFw3_GPLCq_i-v65QULls',
    appId: '1:548774862186:android:1aba0c0936b38d43ffd913',
    messagingSenderId: '548774862186',
    projectId: 'talkhands-7d320',
    databaseURL: 'https://talkhands-7d320-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'talkhands-7d320.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALx9ril9nP_FYmN6ub8D7a6kfvg40DNkg',
    appId: '1:548774862186:ios:d49b55827c3107deffd913',
    messagingSenderId: '548774862186',
    projectId: 'talkhands-7d320',
    databaseURL: 'https://talkhands-7d320-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'talkhands-7d320.appspot.com',
    iosClientId: '548774862186-j6grht54ngvaicpbo9k5n715phnp5bi3.apps.googleusercontent.com',
    iosBundleId: 'com.signier.signierDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALx9ril9nP_FYmN6ub8D7a6kfvg40DNkg',
    appId: '1:548774862186:ios:d49b55827c3107deffd913',
    messagingSenderId: '548774862186',
    projectId: 'talkhands-7d320',
    databaseURL: 'https://talkhands-7d320-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'talkhands-7d320.appspot.com',
    iosClientId: '548774862186-j6grht54ngvaicpbo9k5n715phnp5bi3.apps.googleusercontent.com',
    iosBundleId: 'com.signier.signierDemo',
  );
}
